language: python
branches:
only:
  - master
  - exp-travis
python:
  - "3.5"
  - "3.6"

cache:
  directories:
      - $HOME/.pip-cache/

addons:
  apt:
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake

before_install:
  - sudo chmod 777 /usr/local/bin
  - git clone https://github.com/veg/tn93.git
  - cd tn93/ && cmake ./ && make install && cd ../

install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install biopython
  - pip install numpy
  - travis_wait
  - pip -v install scipy
  - pip install coveralls

script: 
  - python setup.py install
  - python -c 'import hivtrace'
  - nosetests --with-coverage
notifications:
    email:
        recipients:
             - saw111@pitt.edu
#            - steven@stevenweaver.org
#            - jwertheim@ucsd.edu
#            - spond@temple.edu
        on_success: change
        on_failure: always

after_success:
  - coveralls
